#!/bin/bash

if [[ $# -lt 1 ]] || [[ ! -d $1 ]]; then
    echo "$0 <dir>"
    exit 1
fi

BG="$(find $1 -type f | shuf -n 1)"

# swww img 
PROGRAM="swww-daemon"

# Check if the program is running
if pgrep "$PROGRAM" >/dev/null; then
	swww img "$BG" --transition-fps 60 --transition-step 90 --transition-type wipe --transition-angle 100
else
	swww init && swww img "$BG" --transition-fps 60 --transition-step 90 --transition-type wipe --transition-angle 100
fi
